### ISSUE TITLE
 Design and develop a user interface for employers to review and select candidates who have applied to their job offers

### ISSUE THREAD

**Issue by nandinibibra-96** [arpit1102/JAN-Soen6011summer2023#10]
This is a sub task for User Story https://github.com/arpit1102/JAN-Soen6011summer2023/issues/4

Description :

This task involves designing and implementing a user interface that allows employers to review candidate applications for their job offers. The interface should provide a clear overview of candidate details and enable employers to select candidates for further consideration

Story Points : 8

**Comment by harika89** [comment]
Pushed necessary code to the branch and completed the task
