### ISSUE TITLE
Create a README.md file

### ISSUE THREAD

**Issue by rajatjc** [arpit1102/JAN-Soen6011summer2023#2]
As a project team member, I want to create a README.md file to provide essential information and instructions about the project. The README.md file serves as a documentation resource for developers, stakeholders, and potential contributors, offering a quick overview of the project, its purpose, and how to get started.

This is a sub-user story/ task under #1

We will carry out the following steps for the issue :

1. File Creation: Create a new file named README.md at the root of the project repository.
2. Purpose and Overview: Write a brief introduction explaining the purpose and goals of the project. Describe the problem the project aims to solve and the intended benefits it offers.
3. Contact Information: Include contact details for project maintainers or the development team, allowing users to reach out for support, questions, or collaboration opportunities.

By completing this sub-task, the project will have a well-documented README.md file that effectively communicates essential information about the project. This file serves as a go-to resource for anyone interacting with the project, fostering better understanding, collaboration, and overall project success.

**Comment by nandinibibra-96** [comment]
This task is completed , each team member has updated the Readme file with their assigned work.
