### ISSUE TITLE
Design and create an intuitive and visually appealing user interface for student/candidate registration and account creation

### ISSUE THREAD

**Issue by nandinibibra-96** [arpit1102/JAN-Soen6011summer2023#26]
This is a sub task for User Story https://github.com/arpit1102/JAN-Soen6011summer2023/issues/5

Description :

This task focuses on designing and implementing a user-friendly interface that allows students/candidates to register and create their accounts. The interface should be visually appealing and intuitive to guide them through the registration process smoothly.

Story Points : 5

**Comment by harika89** [comment]
Designed required interface and pushed it
