### ISSUE TITLE
Develop a user-friendly login interface for students/candidates, upload resume,ensuring secure access to their accounts

### ISSUE THREAD

**Issue by nandinibibra-96** [arpit1102/JAN-Soen6011summer2023#27]
This is a sub task for User Story https://github.com/arpit1102/JAN-Soen6011summer2023/issues/5

Description :
This story involves creating a login interface that enables students/candidates to securely access their accounts. It should also provide functionality to upload their resumes, ensuring the confidentiality and integrity of the uploaded documents.

Story Points : 5

**Comment by harika89** [comment]
Completed the issue
