### ISSUE TITLE
Create a visually appealing and easy-to-navigate interface for students/candidates to browse job offers

### ISSUE THREAD

**Issue by nandinibibra-96** [arpit1102/JAN-Soen6011summer2023#28]
This is a sub task for User Story https://github.com/arpit1102/JAN-Soen6011summer2023/issues/5

Description :
This task aims to design and develop a user interface that allows students/candidates to browse through available job offers. The interface should be visually appealing and provide an easy-to-navigate experience for them to explore job opportunities.

Story Points : 5

**Comment by harika89** [comment]
completed the code of this issue
