### ISSUE TITLE
Design and develop an intuitive interface for candidates to apply for job offers, including a submission form and confirmation message

### ISSUE THREAD

**Issue by nandinibibra-96** [arpit1102/JAN-Soen6011summer2023#29]
This is a sub task for User Story https://github.com/arpit1102/JAN-Soen6011summer2023/issues/5

Description :
This task focuses on creating an intuitive interface for candidates to apply for job offers. It involves designing and implementing a submission form that collects relevant information and providing a confirmation message to acknowledge successful application submission.

Story Points : 5

**Comment by harika89** [comment]
completed the code in this issue
