### ISSUE TITLE
Design and create the necessary database schema to store student/candidate registration details

### ISSUE THREAD

**Issue by nandinibibra-96** [arpit1102/JAN-Soen6011summer2023#36]
This is a sub task for User Story https://github.com/arpit1102/JAN-Soen6011summer2023/issues/5

Description :

This task involves designing and creating a database schema to securely store student/candidate registration details. It includes defining the structure of the tables and relationships needed to store the necessary information.

Story Points : 3

**Comment by jatishbhatia** [comment]
The relevant code to create the database for candidate registration is completed and pushed.
