### ISSUE TITLE
Develop the database structure to securely store and retrieve candidate login credentials

### ISSUE THREAD

**Issue by nandinibibra-96** [arpit1102/JAN-Soen6011summer2023#37]
This is a sub task for User Story https://github.com/arpit1102/JAN-Soen6011summer2023/issues/5

Description :
This task focuses on developing the database structure to securely store and retrieve candidate login credentials. It ensures the confidentiality and integrity of the stored credentials.

Story Points : 3

**Comment by jatishbhatia** [comment]
The code to store and retrieve login credentials will be used for both applicant and employer. It is completed.
