### ISSUE TITLE
Design and implement the database schema for storing candidate resume data, including the necessary tables and relationships

### ISSUE THREAD

**Issue by nandinibibra-96** [arpit1102/JAN-Soen6011summer2023#38]
This is a sub task for User Story https://github.com/arpit1102/JAN-Soen6011summer2023/issues/5

Description :

This task involves designing and implementing a database schema to store candidate resume data. It includes defining the structure and relationships for storing the necessary information related to candidate resumes.

Story Points : 5

**Comment by jatishbhatia** [comment]
A column for resume in the database is added. The form field was already added with other form functionalities.

**Comment by jatishbhatia** [comment]
All the relevant feature to candidate resume has been added.
