### ISSUE TITLE
Create the necessary database tables and relationships to store applied jobs details and their associated offers

### ISSUE THREAD

**Issue by nandinibibra-96** [arpit1102/JAN-Soen6011summer2023#39]
This is a sub task for User Story https://github.com/arpit1102/JAN-Soen6011summer2023/issues/5

Description :

This task focuses on creating the required database tables and relationships to store job offer details securely. It ensures an organized structure for storing job-related information.

Story Points : 5

**Comment by jatishbhatia** [comment]
Relevant code is completed to create tables for tracking job applications and offers.
