### ISSUE TITLE
Implement database operations to allow the candidate to update its profile and details

### ISSUE THREAD

**Issue by nandinibibra-96** [arpit1102/JAN-Soen6011summer2023#40]
This is a sub task for User Story https://github.com/arpit1102/JAN-Soen6011summer2023/issues/5

Description :
This task involves implementing database operations to track and manage candidate job applications and their associated job offers. It includes efficient storage, retrieval, and management of application data.

Story Points : 8

**Comment by jatishbhatia** [comment]
Relevant code is completed and pushed related to candidate update and changes.
