### ISSUE TITLE
As a candidate I would like keep a track of the post by employers, As an employer I would like to track application by candidates

### ISSUE THREAD

**Issue by nandinibibra-96** [arpit1102/JAN-Soen6011summer2023#45]
To complete this user story , following tasks will have to be completed :-

- [ ] https://github.com/arpit1102/JAN-Soen6011summer2023/issues/71
- [x] #72 
- [x] #73 
- [x] #74 
- [x] #75 
- [x] #76 

Story Points : 22

Risk: Data Breach
Impact: High
Probability: Medium
Counter measure: Implement strong encryption measures for sensitive candidate data and apply strict access controls to prevent unauthorized access.

Risk: Poor User Experience
Impact: Medium
Probability: Low
Counter measure: Conduct usability testing, gather feedback from candidates, and iterate on the user interface design to enhance the overall user experience.

Risk: Integration Challenges
Impact: Medium
Probability: Medium
Counter measure: Implement well-defined integration interfaces, perform thorough integration testing, and establish clear communication channels between development teams to address any integration issues promptly.

Risk: Database Failure
Impact: High
Probability: Low
Counter measure: Implement a well designed database with correct foreign keys and primary keys, relationships

**Comment by arpit1102** [comment]
Completed.
