### ISSUE TITLE
 Implement backend functionality for retrieving and displaying candidate profiles and jobs

### ISSUE THREAD

**Issue by nandinibibra-96** [arpit1102/JAN-Soen6011summer2023#55]
This is a sub task for User Story https://github.com/arpit1102/JAN-Soen6011summer2023/issues/6

Description :

 This tasks involved implementing a secure admin interface to browse user profiles and job postings. It includes backend development with APIs for handling data, frontend design ,user authentication, responsive design, error handling, and robust testing to ensure a user-friendly and protected system.

Story Points : 8

**Comment by jatishbhatia** [comment]
Added relevant code. Completed.
