### ISSUE TITLE
Design and create a visually appealing and user-friendly employer registration form

### ISSUE THREAD

**Issue by nandinibibra-96** [arpit1102/JAN-Soen6011summer2023#7]
This is a sub task for User Story https://github.com/arpit1102/JAN-Soen6011summer2023/issues/4

Description :

This task involves designing and implementing an employer registration form that is visually appealing and easy to use for employers. The form should collect necessary information for registration and ensure validation of the input data.

Story Points : 5

**Comment by harika89** [comment]
Registration form is created and pushed to Sprint2
