### ISSUE TITLE
Create a visually appealing and easy-to-navigate candidate browsing interface

### ISSUE THREAD

**Issue by nandinibibra-96** [arpit1102/JAN-Soen6011summer2023#8]
This is a task under the user story #4 

Description:

This task requires designing and developing a user interface that allows employers to browse through candidate profiles. The interface should be visually appealing, intuitive, and provide easy navigation for employers to review candidate information

Story Points : 5

**Comment by harika89** [comment]
Created a responsive interface to navigate candidate browsing interface with front-end and back-end.
